app = "linux-dev-server"
primary_region = "ord"
primary_region = "lax"

[build]

[env]

[[services]]
  protocol = "tcp"
  internal_port = 2222
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 22

[[vm]]
  cpu_kind = "performance"
  cpus = 16
  memory_mb = 32768

[mounts]
  source = "persistent"
  destination = "/persistent"
